name: cards
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  bloc: ^8.1.4
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/cards/
    - assets/background/

flutter_gen:
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  integrations:
    flutter_svg: true